# Generated by Django 4.2.5 on 2023-10-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_pub',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
